//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_MVP_Socks4.SocksServise {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.Web.org/", ConfigurationName="SocksServise.ServiceSocks2")]
    public interface ServiceSocks2 {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse checkDB(WindowsFormsApp_MVP_Socks4.SocksServise.checkDB request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse> checkDBAsync(WindowsFormsApp_MVP_Socks4.SocksServise.checkDB request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse save(WindowsFormsApp_MVP_Socks4.SocksServise.save request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse> saveAsync(WindowsFormsApp_MVP_Socks4.SocksServise.save request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp_MVP_Socks4.SocksServise.readResponse read(WindowsFormsApp_MVP_Socks4.SocksServise.read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readResponse> readAsync(WindowsFormsApp_MVP_Socks4.SocksServise.read request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse delete(WindowsFormsApp_MVP_Socks4.SocksServise.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse> deleteAsync(WindowsFormsApp_MVP_Socks4.SocksServise.delete request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse readAll(WindowsFormsApp_MVP_Socks4.SocksServise.readAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse> readAllAsync(WindowsFormsApp_MVP_Socks4.SocksServise.readAll request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDB", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class checkDB {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public checkDB() {
        }
        
        public checkDB(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDBResponse", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class checkDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public checkDBResponse() {
        }
        
        public checkDBResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.Web.org/")]
    public partial class type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp_MVP_Socks4.SocksServise.type[] arg0;
        
        public save() {
        }
        
        public save(WindowsFormsApp_MVP_Socks4.SocksServise.type[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class saveResponse {
        
        public saveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public read() {
        }
        
        public read(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class readResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp_MVP_Socks4.SocksServise.type @return;
        
        public readResponse() {
        }
        
        public readResponse(WindowsFormsApp_MVP_Socks4.SocksServise.type @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public delete() {
        }
        
        public delete(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class deleteResponse {
        
        public deleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAll", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class readAll {
        
        public readAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAllResponse", WrapperNamespace="http://soap.Web.org/", IsWrapped=true)]
    public partial class readAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.Web.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp_MVP_Socks4.SocksServise.type[] @return;
        
        public readAllResponse() {
        }
        
        public readAllResponse(WindowsFormsApp_MVP_Socks4.SocksServise.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSocks2Channel : WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSocks2Client : System.ServiceModel.ClientBase<WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2>, WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2 {
        
        public ServiceSocks2Client() {
        }
        
        public ServiceSocks2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSocks2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSocks2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSocks2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.checkDB(WindowsFormsApp_MVP_Socks4.SocksServise.checkDB request) {
            return base.Channel.checkDB(request);
        }
        
        public bool checkDB(string arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.checkDB inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.checkDB();
            inValue.arg0 = arg0;
            WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse retVal = ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).checkDB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse> WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.checkDBAsync(WindowsFormsApp_MVP_Socks4.SocksServise.checkDB request) {
            return base.Channel.checkDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.checkDBResponse> checkDBAsync(string arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.checkDB inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.checkDB();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).checkDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.save(WindowsFormsApp_MVP_Socks4.SocksServise.save request) {
            return base.Channel.save(request);
        }
        
        public void save(WindowsFormsApp_MVP_Socks4.SocksServise.type[] arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.save inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.save();
            inValue.arg0 = arg0;
            WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse retVal = ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse> WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.saveAsync(WindowsFormsApp_MVP_Socks4.SocksServise.save request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.saveResponse> saveAsync(WindowsFormsApp_MVP_Socks4.SocksServise.type[] arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.save inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.save();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp_MVP_Socks4.SocksServise.readResponse WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.read(WindowsFormsApp_MVP_Socks4.SocksServise.read request) {
            return base.Channel.read(request);
        }
        
        public WindowsFormsApp_MVP_Socks4.SocksServise.type read(int arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.read inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.read();
            inValue.arg0 = arg0;
            WindowsFormsApp_MVP_Socks4.SocksServise.readResponse retVal = ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).read(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readResponse> WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.readAsync(WindowsFormsApp_MVP_Socks4.SocksServise.read request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readResponse> readAsync(int arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.read inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.read();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.delete(WindowsFormsApp_MVP_Socks4.SocksServise.delete request) {
            return base.Channel.delete(request);
        }
        
        public void delete(int arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.delete inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.delete();
            inValue.arg0 = arg0;
            WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse retVal = ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse> WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.deleteAsync(WindowsFormsApp_MVP_Socks4.SocksServise.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.deleteResponse> deleteAsync(int arg0) {
            WindowsFormsApp_MVP_Socks4.SocksServise.delete inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.delete();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.readAll(WindowsFormsApp_MVP_Socks4.SocksServise.readAll request) {
            return base.Channel.readAll(request);
        }
        
        public WindowsFormsApp_MVP_Socks4.SocksServise.type[] readAll() {
            WindowsFormsApp_MVP_Socks4.SocksServise.readAll inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.readAll();
            WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse retVal = ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).readAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse> WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2.readAllAsync(WindowsFormsApp_MVP_Socks4.SocksServise.readAll request) {
            return base.Channel.readAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_MVP_Socks4.SocksServise.readAllResponse> readAllAsync() {
            WindowsFormsApp_MVP_Socks4.SocksServise.readAll inValue = new WindowsFormsApp_MVP_Socks4.SocksServise.readAll();
            return ((WindowsFormsApp_MVP_Socks4.SocksServise.ServiceSocks2)(this)).readAllAsync(inValue);
        }
    }
}
